# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

## Assuming that list_ and array_list are two separate variables, one declared as a Python list and the other as a NumPy array, then yes, there is a difference in their data types.

In [1]:
import numpy as np

list_ = [1, 2, 3, 4, 5]

array_list = np.array([1, 2, 3, 4, 5])

# Print the data types of both variables
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))


Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
import numpy as np

# Declare a Python list
list_ = [1, 2, 3, 4, 5]

# Declare a NumPy array
array_list = np.array([1, 2, 3, 4, 5])

# Print the data type of each element in 'list_'
print("Data type of elements in 'list_':")
for element in list_:
    print(type(element))

# Print the data type of each element in 'array_list'
print("\nData type of elements in 'array_list':")
for element in array_list:
    print(type(element))


Data type of elements in 'list_':
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data type of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Q3. Considering the following changes in the variable, array_list:


In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
array_list

array([1, 2, 3, 4, 5])

# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
# Consider the below code to answer further questions:

In [11]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_list)
print(num_array)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [5]:
import numpy as np

# Declare a NumPy array
num_array = np.array([[1, 2, 3], [4, 5, 6]])

# Find the shape of 'num_array'
shape = num_array.shape

# Find the size of 'num_array'
size = num_array.size

# Print the shape and size of 'num_array'
print("Shape of 'num_array':", shape)
print("Size of 'num_array':", size)


Shape of 'num_array': (2, 3)
Size of 'num_array': 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [6]:
import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [7]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
